name: Upload file to gist
on:
  push:
    branches:
      - main
    paths:
      - 'Cargo.toml'

jobs:
  build:
    name: Build
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Setup Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Generate Json File
        run: node scripts/generate.js
      - name: Upload 
        uses: popsiclestick/gist-sync-action@v1.2.0
        id: sync
        with:
          auth: ${{ secrets.RSPACK_COMPAT_GIST }}
          github_file: 'rspack-compat.json'
